name: ChrisHanse
favicon: null
layout_spectrum: 0.9991
typography_spectrum: 0.51627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3ccf8'
    - '#5e6a3c'
    - '#1e1f24'
    - '#213f87'
    - '#ecf1ed'
  brandStrength: 0.040789148304611444
  lightness: 0.5276422945316881
  saturation: 0.2462447346188128
  rhythmicContrast: 0.6915269680321217
purpose: []
